### PR TITLE
Added work order entity

### PR DESCRIPTION
**Pull request by TIVMOF**

### CODE REVIEW

**Review by nedelcho-delchev-tues — CHANGES_REQUESTED** [review]
- What is the difference between `Operator` and `Executor` 
- `Referances` should be `Reference`
- `Number` needs to also have a "global" entity import `import { NumberGeneratorService } from "/codbex-number-generator/service/generator";`
- `Number` has a calculated field and the parameter right now is `4` this isn't correct, see `codbex-number-generator -> data -> numbers.csv` for the correct parameter, if the corresponding entity is not present in the csv add it manually at the end.
- `Currency`, `PaymentMethod`, `SentMethod`, `WorkOrderStatus`, `Operator` should be `Dropdown` widget
- If a `Text field` is more than 100 chars the widget type should be `Text box`
- `Disscount` typo

**Comment by nedelcho-delchev-tues** [comment]
What is the purpose of the property `SalesOrder` in the `WorkOrder` entity, right now its just a text field ?

**Comment by TIVMOF** [comment]
> * What is the difference between `Operator` and `Executor`
> 

Operator is the one that made the WorkOrder. Executor is the one who performs the task. Should I name him differently or remove it?

**Comment by TIVMOF** [comment]
>     * What is the purpose of the property `SalesOrder` in the `WorkOrder` entity, right now its just a text field ?

The SalesOrder property references any products that may have been used in the completion of the task.

**Review by nedelcho-delchev-tues — APPROVED** [review]
lgtm 👍

**Pull request merged**
